update

diff --git a/setup-consolefont.in b/setup-consolefont.in
--- a/setup-consolefont.in
+++ b/setup-consolefont.in
@@ -1,23 +1,43 @@
 #!/bin/sh
 
-PROGRAM=setup-consolefont
+if [ "$(id -u)" -ne 0 ] || [ "$DOAS_USER" = "root" ] || [ "$DOAS_USER" = "" ]; then
+   echo "run this script as a regular user using doas"
+   exit 1
+fi
+
+#########################################################################################
+# PROGRAM METADATA
+#########################################################################################
+
+PROGRAM=$(basename "$0")
+PROGRAM_DIR=@PROGRAM_DIR@
 VERSION=@VERSION@
 
-# PREFIX=
-# . $PREFIX/lib/libalpine.sh
-# . $PREFIX/lib/libusralpine.sh
+#########################################################################################
+# PROGRAM DEPENDENCIES
+#########################################################################################
 
-APKPKGS=terminus-font
-FONT=ter-132n.psf.gz
+. "@LIB_DIR@/libusralpine.sh"
 
-echo "Adding font"
-apk add "$APKPKGS" || exit 1
+#########################################################################################
+# PROGRAM DATA
+#########################################################################################
 
-echo "Using font"
-setfont /usr/share/consolefonts/$FONT || exit 2
+FONTPKG=terminus-font
+FONT=ter-116n.psf.gz
 
-echo "Overwriting /etc/conf.d/consolefont with custom configuration"
-cat >/etc/conf.d/consolefont <<-__EOF__
+#########################################################################################
+# PROGRAM 
+#########################################################################################
+
+header "$PROGRAM"
+
+
+step "adding font"
+apk add "$FONTPKG" ||  die "consolefont setup - failed to add $FONTPKG."
+
+step "adding font configuration"
+{ cat >/etc/conf.d/consolefont <<-__EOF__
 # The consolefont service is not activated by default. If you need to
 # use it, you should run "rc-update add consolefont boot" as root.
 #
@@ -33,6 +53,10 @@ consolefont="default8x16.psf.gz"
 # alpine-user-conf: setup-consolefont
 consolefont="$FONT"
 __EOF__
+} ||  die "consolefont setup - failed to add font configuration."
 
-echo "Adding consolefont service to boot"
-rc-update add consolefont boot
+step "adding consolefont service to boot"
+rc-update add consolefont boot || die "consolefont setup - failed to add consolefont service to boot."
+
+step "setting font"
+setfont "/usr/share/consolefonts/$FONT" || warn "consolefont setup - failed to set $FONT."
diff --git a/setup-dbus.in b/setup-dbus.in
--- a/setup-dbus.in
+++ b/setup-dbus.in
@@ -1,7 +1,7 @@
 #!/bin/sh
 
-if [ $(id -u) -ne 0 ]; then
-   echo "this script must be run as root"
+if [ "$(id -u)" -ne 0 ] || [ "$DOAS_USER" = "root" ] || [ "$DOAS_USER" = "" ]; then
+   echo "run this script as a regular user using doas"
    exit 1
 fi
 
@@ -25,6 +25,7 @@ VERSION=@VERSION@
 
 header "$PROGRAM"
 
+
 step "adding dbus"
 apk add dbus dbus-openrc || die "dbus setup - failed to install dbus"
 
@@ -32,4 +33,4 @@ step "adding dbus service to default"
 rc-update add dbus default || die "dbus setup - failed to add dbus service to default"
 
 step "starting dbus service"
-rc-service dbus start || warn "dbus setup - failed to start dbus service. please run manually."
+rc-service dbus start || die "dbus setup - failed to start dbus service"
diff --git a/setup-pipewire.in b/setup-pipewire.in
--- a/setup-pipewire.in
+++ b/setup-pipewire.in
@@ -1,7 +1,7 @@
 #!/bin/sh
 
-if [ $(id -u) -ne 0 ]; then
-   echo "this script must be run as root"
+if [ "$(id -u)" -ne 0 ] || [ "$DOAS_USER" = "root" ] || [ "$DOAS_USER" = "" ]; then
+   echo "run this script as a regular user using doas"
    exit 1
 fi
 
@@ -12,12 +12,13 @@ fi
 PROGRAM=$(basename "$0")
 PROGRAM_DIR=@PROGRAM_DIR@
 VERSION=@VERSION@
+LIB_DIR=@LIB_DIR@
 
 #########################################################################################
 # PROGRAM DEPENDENCIES
 #########################################################################################
 
-. "@LIB_DIR@/libusralpine.sh"
+. "$LIB_DIR/libusralpine.sh"
 
 #########################################################################################
 # PREREQUISITES 
@@ -37,16 +38,22 @@ header "$PROGRAM"
 
 
 step "adding pipewire"
-apk add pipewire pipewire-alsa pipewire-pulse wireplumber || die "pipeware setup - failed to install pipewire" 
+apk add pipewire pipewire-alsa pipewire-pulse wireplumberc rtkit || die "pipeware setup - failed to install pipewire" 
+
+step "adding root to rtkit group"
+addgroup root rtkit || die "pipewire setup - failed to add root to rtkit group"
+
+step "adding $DOAS_USER to rtkit group"
+addgroup "$DOAS_USER" rtkit || die "pipewire setup - failed to add $DOAS_USER to rtkit group"
 
 step "adding root to audio group"
-addgroup root audio
+addgroup root audio || die "pipewire setup - failed to add root to audio group"
 
 step "adding $DOAS_USER to audio group"
-addgroup "$DOAS_USER" audio
+addgroup "$DOAS_USER" audio || die "pipewire setup - failed to add $DOAS_USER to audio group"
 
 step "restarting dbus service"
-rc-service dbus restart || warn "pipewire setup - failed to restart dbus service. please restart manually."
+rc-service dbus restart || die "pipewire setup - failed to restart dbus service"
 
 footer_start
 footer_text "start pipewire with /usr/libexec/pipewire-launcher"
diff --git a/setup-seatd.in b/setup-seatd.in
--- a/setup-seatd.in
+++ b/setup-seatd.in
@@ -1,7 +1,7 @@
 #!/bin/sh
 
-if [ $(id -u) -ne 0 ]; then
-   echo "this script must be run as root"
+if [ "$(id -u)" -ne 0 ] || [ "$DOAS_USER" = "root" ] || [ "$DOAS_USER" = "" ]; then
+   echo "run this script as a regular user using doas"
    exit 1
 fi
 
@@ -12,12 +12,13 @@ fi
 PROGRAM=$(basename "$0")
 PROGRAM_DIR=@PROGRAM_DIR@
 VERSION=@VERSION@
+LIB_DIR=@LIB_DIR@
 
 #########################################################################################
 # PROGRAM DEPENDENCIES
 #########################################################################################
 
-. "@LIB_DIR@/libusralpine.sh"
+. "$LIB_DIR/libusralpine.sh"
 
 #########################################################################################
 # PROGRAM 
@@ -29,14 +30,14 @@ header "$PROGRAM"
 step "adding seatd"
 apk add seatd || die "seatd setup - failed to install seatd"
 
+step "adding root to seat group"
+adduser root seat || die "seatd setup - failed to add root to seat group"
+
+step "adding $DOAS_USER to seat group"
+adduser "$DOAS_USER" seat || die "seatd setup - failed to add $DOAS_USER to seat group"
+
 step "adding seatd service to default"
 rc-update add seatd default || die "seatd setup - failed to add seatd service to default"
 
 step "starting seatd service"
-rc-service seatd start || warn "seatd setup - failed to start seatd service. please run manually."
-
-step "adding root to seat group"
-adduser root seat || warn "seatd setup - failed to add root to seat group. please add manually."
-
-step "adding $DOAS_USER to seat group"
-adduser $DOAS_USER seat || warn "seatd setup - failed to add $DOAS_USER to seat group. please add manually."
+rc-service seatd start || die "seatd setup - failed to start seatd service"
diff --git a/setup-sway.in b/setup-sway.in
--- a/setup-sway.in
+++ b/setup-sway.in
@@ -1,7 +1,7 @@
 #!/bin/sh
 
-if [ $(id -u) -ne 0 ]; then
-   echo "this script must be run as root"
+if [ "$(id -u)" -ne 0 ] || [ "$DOAS_USER" = "root" ] || [ "$DOAS_USER" = "" ]; then
+   echo "run this script as a regular user using doas"
    exit 1
 fi
 
@@ -12,12 +12,13 @@ fi
 PROGRAM=$(basename "$0")
 PROGRAM_DIR=@PROGRAM_DIR@
 VERSION=@VERSION@
+LIB_DIR=@LIB_DIR@
 
 #########################################################################################
 # PROGRAM DEPENDENCIES
 #########################################################################################
 
-. "@LIB_DIR@/libusralpine.sh"
+. "$LIB_DIR/libusralpine.sh"
 
 #########################################################################################
 # PREREQUISITES 
@@ -26,13 +27,11 @@ VERSION=@VERSION@
 echo
 task "1. setup-dbus"
 task "2. setup-seatd"
-task "3. setup-pipewire"
-task "4. setup-udev"
-task "5. setup-sway"
+task "3. setup-udev"
+task "4. setup-sway"
 
 "$PROGRAM_DIR/setup-dbus" || die "sway setup - failed to install prerequisite: dbus" 
 "$PROGRAM_DIR/setup-seatd" || die "sway setup - failed to install prerequisite: seatd"
-"$PROGRAM_DIR/setup-pipewire" || die "sway setup - failed to install prerequisite: pipewire" 
 
 #########################################################################################
 # PROGRAM 
@@ -62,7 +61,7 @@ apk add sway \
       swayidle || die "sway setup - failed to install sway"
 
 step "restarting dbus service"
-rc-service dbus restart || warn "sway setup - failed to restart dbus service. please restart manually."
+rc-service dbus restart || die "sway setup - failed to restart dbus service"
 
 footer_start
 footer_text "remember to copy /etc/sway/config to ~/.config/sway/config"
